#!/bin/bash

### BEGIN INIT INFO
# Provides:          BatteryShutdown
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Apagado seguro al 1% de batería
### END INIT INFO

red_on() { echo 1 > /sys/class/power_supply/axp2202-battery/led_test; }
red_off() { echo 0 > /sys/class/power_supply/axp2202-battery/led_test; }
green_on() { echo 1 > /sys/class/power_supply/axp2202-battery/work_led; }
green_off() { echo 0 > /sys/class/power_supply/axp2202-battery/work_led; }

monitor_battery() {
    while true; do
        capacity=$(cat /sys/class/power_supply/axp2202-battery/capacity 2>/dev/null)
        status=$(cat /sys/class/power_supply/axp2202-battery/status 2>/dev/null)
        
        if [ "$status" = "Charging" ] && { [ -f /tmp/lowbattery10 ] || [ -f /tmp/lowbattery5 ]; }; then
            rm -f /tmp/lowbattery*
            red_off
            green_on
        elif [ "$capacity" -le 10 ] && [ "$capacity" -gt 5 ] && [ ! -f /tmp/lowbattery10 ] && [ "$status" == "Discharging" ]; then
            logger "Battery is low to 10%"
            rumble-test && sleep 0.3
            rumble-test && sleep 0.3
            rumble-test
            green_off
            red_on
            
            touch /tmp/lowbattery10
        elif [ "$capacity" -le 5 ] && [ "$capacity" -gt 1 ] && [ ! -f /tmp/lowbattery5 ] && [ "$status" == "Discharging" ]; then
            logger "Battery is low to 5%"
            rumble-test && sleep 0.3
            rumble-test && sleep 0.3
            rumble-test
            green_off
            red_on
            
            touch /tmp/lowbattery5
        elif [ "$capacity" -le 1 ] && [ "$status" == "Discharging" ]; then
            logger "Battery at 1% - Initiating safe shutdown protocol"
            rumble-test && sleep 0.3
            rumble-test && sleep 0.3
            rumble-test
            
            pkill -9 retroarch
            pkill -9 retroarch32
            
            # Disable swap
            swapoff -a
            
            # Unmount non-essential partitions
            umount -a -t ext4,vfat,loop -l >/dev/null 2>&1
            
            # shutdown the system
            shutdown -h now
            exit 0
        fi
        sleep 30
    done
}

case "$1" in
    start)
        monitor_battery &
        ;;
    stop)
        pkill -f "99batteryshutdown"
        ;;
    *)
        echo "Uso: $0 {start|stop}"
        exit 1
        ;;
esac
