#!/bin/bash

### BEGIN INIT INFO
# Provides:          BatteryShutdown
# Required-Start:    $all
# Required-Stop:
# Default-Start:     5
# Default-Stop:      0 1 2 3 4 6
# Short-Description: Apagado seguro al 1% de bateria
### END INIT INFO

PIDFILE="/var/run/battmon.pid"

case "$1" in
    start)
        if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
            echo "BatteryShutdown already running"
            exit 0
        fi
        /usr/bin/battmon &
        echo $! > "$PIDFILE"
        ;;
    stop)
        if [ -f "$PIDFILE" ]; then
            kill $(cat "$PIDFILE") 2>/dev/null
            rm -f "$PIDFILE"
        else
            echo "No BatteryShutdown process to stop"
        fi
        ;;
    *)
        echo "Uso: $0 {start|stop}"
        exit 1
        ;;
esac
